GET endpoints
Hargeon/videocmprs pull request #17
Opened 2021-11-04 01:12 UTC by Hargeon

Add GET endpoints for fetching data from front-end

2021-11-18 12:22 UTC, gordonBusyman requested changes
1. Do something with the interfaces.. It's a mess
2. Please add `PR_TEMPLATE` and use it

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/repository/request/repository.go
> +		repo.unmarshalDBVideo(origin)
There is alternative to it, called DTO (Data Transfer Object) - check and use if u like it

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/repository/request/repository.go
> +func (repo *Repository) List(ctx context.Context, params *query.Params) ([]interface{}, error) {
Mate, split the file to `list.go` `update.go` `retrieve.go` and `create.go`
Do the same for the rest of entities

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/repository/request/resource.go
> +	ResolutionX int   `jsonapi:"attr,resolution_x" validate:"required_if=Bitrate 0 RatioX 0 RatioY 0,required_with=ResolutionY"` //nolint:lll
What is `//nolint:lll` ??

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/repository/user/resource.go
> +		"self": fmt.Sprintf("%s/api/v1/auth/me", os.Getenv("BASE_URL")),
```suggestion
		"self": fmt.Sprintf("%s/api/v1/users/%v", os.Getenv("BASE_URL"), r.ID),
```

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/repository/video/repository.go
> +	if video.BitrateDB.Valid {
DTO

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/service/auth/authorization.go
> +// Service ...
Comment

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/service/auth/authorization.go
> +// Retrieve return user params
```suggestion
// Retrieve return user resource
```

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/service/service.go
> +	Retrieve(ctx context.Context, id int64) (jsonapi.Linkable, error)
```suggestion
	Retriever
```

2021-11-18 12:22 UTC, gordonBusyman commented on pkg/service/service.go
>  	Retrieve(ctx context.Context, resource jsonapi.Linkable) (jsonapi.Linkable, error)
```suggestion
	Retrieve(ctx context.Context, id int64) (jsonapi.Linkable, error)
```

2021-11-23 23:07 UTC, Hargeon commented on pkg/repository/video/repository.go
> +	if video.BitrateDB.Valid {
Done

2021-11-23 23:07 UTC, Hargeon commented on pkg/repository/request/repository.go
> +		repo.unmarshalDBVideo(origin)
Done

2021-11-23 23:07 UTC, Hargeon commented on pkg/repository/request/repository.go
> +func (repo *Repository) List(ctx context.Context, params *query.Params) ([]interface{}, error) {
Done

2021-11-23 23:09 UTC, Hargeon commented on pkg/repository/request/resource.go
> +	ResolutionX int   `jsonapi:"attr,resolution_x" validate:"required_if=Bitrate 0 RatioX 0 RatioY 0,required_with=ResolutionY"` //nolint:lll
The line is more than 120 characters. This comment disable linter in lines

2021-11-23 23:09 UTC, Hargeon commented on db/migrations/common/20211019214146_requests.sql
>  CREATE TABLE IF NOT EXISTS requests (
Done

2021-11-24 09:44 UTC, gordonBusyman commented on pkg/repository/video/resource.go
> +	if r.ID.Valid {
```
return &Resource{
ID: dto.ID.Int64,
Name: dto.Name.String,
...
```

2021-11-24 16:51 UTC, Hargeon commented on db/migrations/common/20211019214146_requests.sql
>      status VARCHAR(255) NOT NULL DEFAULT 'original_in_review',
Done

2021-11-24 16:53 UTC, Hargeon commented on pkg/service/auth/authorization.go
> +// Service ...
Fixed in other pr

2021-11-28 16:45 UTC, merged